### ISSUE TITLE
Separate base runner for committee and other runners

### ISSUE THREAD

**Issue by MatheusFranco99** [ssvlabs/ssv-spec#488] opened 2024-08-19 11:45 UTC
think of separating the base for committee and other runners. Since other runners will never recv more than one share, it looks weird that their func signature can recv a map of shares.

_Originially posted by @y0sher in https://github.com/ssvlabs/ssv-spec/pull/478#pullrequestreview-2245023908_

**Comment by GalRogozinski** [comment] 2024-09-01 14:52
duplicate of #464

**Closed by GalRogozinski** 2024-09-01 14:52 UTC
Labels: refactor
